### ISSUE TITLE
Getting error in compiling SCSS using gulp using steps provided in Build Tools section

### ISSUE THREAD

**Issue by ShivamS136** [creativetimofficial/now-ui-kit#103]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

SCSS should be compiled and colors should have been changed in CSS files.

# Current Behavior

First I was getting an error in gulp, I used `npm audit fix --force` then different error.

# Failure Information (for bugs)

**Error before audit fix:**
```bash
ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\Users\Sai Ram\Downloads\now-ui-kit-master\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Sai Ram\Downloads\now-ui-kit-master\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Sai Ram\Downloads\now-ui-kit-master\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
```

**Error after audit fix:**
```bash
AssertionError [ERR_ASSERTION]: Task function must be specified
   at Gulp.set [as _setTask] (C:\Users\Sai Ram\Downloads\now-ui-kit-master\node_modules\undertaker\lib\set-task.js:10:3)
   at Gulp.task (C:\Users\Sai Ram\Downloads\now-ui-kit-master\node_modules\undertaker\lib\task.js:13:8)
   at Object.<anonymous> (C:\Users\Sai Ram\Downloads\now-ui-kit-master\gulpfile.js:34:6)
   at Module._compile (internal/modules/cjs/loader.js:1156:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
   at Module.load (internal/modules/cjs/loader.js:1000:32)
   at Function.Module._load (internal/modules/cjs/loader.js:899:14)
   at Module.require (internal/modules/cjs/loader.js:1042:19)
   at require (internal/modules/cjs/helpers.js:77:18)
   at requireOrImport (C:\Users\Sai Ram\AppData\Roaming\npm\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11) {
generatedMessage: false,
code: 'ERR_ASSERTION',
actual: false,
expected: true,
operator: '=='
}
```

## Steps to Reproduce

Follow the guide given in [build tool section](https://demos.creative-tim.com/now-ui-kit/docs/1.0/getting-started/build-tools.html) of the kit.

* Device: HP Notebook
* Operating System: Windows 10 
* Browser and Version: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by dragosct10** [comment]
Hi, @ShivamS136! Thanks for using our products. Please be sure that you have latest versions of npm and nodejs. 

Regards,
Dragos

**Comment by weagle08** [comment]
I'm getting this same error as well in the BLK PRO version. Really need a fix so that I can use the software I paid for. It may be a node version issue. Need an updated version of the BLK Pro using latest NodeJS version 14.

Environment:
Win 10, Node v14.13

**Comment by analuzcervantes** [comment]
Hi @ShivamS136!  
It seems to be related to the Gulp V4, downgrade Gulp version.

1. To downgrade you need to update your package.json with
- `"gulp": "^3.9.1",`

2. And then remove node_module folder and reinstall npm packages
- `rm -rf node_modules`
- `npm install`
